### ISSUE TITLE
Modulated Offset Calculator

### ISSUE THREAD

**Issue by jaisen1** [Navy-Precision-Optial-Interferometer/PYBOC#10]
OK, this one might be hard to describe.  Each night we observe we calculate offsets due to the fringe model degrading due to various reasons such as atmospheric pistoning, array thermal expansion and FDL metrology offsets, i.e. slipping fiducials.  Although we cannot readily measure atmo and thermals they are mostly assumed to be somewhat constant over short time periods.  This leaves FDL metrology which we can account for and align each night, mostly, that we are on sky.  Let's say that we operate the instrument after collecting 3 straight nights of 6-way data and find that on the 4th night there is a constant offset to the predicted baseline offset of about 200 microns, for whatever reason.  It would be nice to be able to just "account" for this additional offset, either positive or negative, by applying a simple offset to predicted baseline offset.  Maybe put an open text box next to the predicted baseline offset in the GUI so that you can input an additional, i.e. diurnal offset, to the baseline offset?  Think of this as a second order differential to what the model is putting out with regard to the initial offset.

**Comment by ermaier** [comment]
Latest update allows for inputting an additional offset term - in microns - for each individual baseline.
