### ISSUE TITLE
Obslog Load Failure

### ISSUE THREAD

**Issue by jaisen1** [Navy-Precision-Optial-Interferometer/PYBOC#4]
Using the 2021-08-25 starlog as an example.  This starlog is data dense but I found that upon loading I was getting an error in the terminal window running PYBOC stating the following...

**Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "offset_calculator_gui_0.3.py", line 182, in import_logs
ValueError: could not convert string to float: '-9:24:55'**

Upon looking for the improper value I found on line 75 of the starlog that the 'type star' was missing a designation.  I deleted that nefarious line in the starlog and PYBOC was then able to load it just fine.  There should probably a check for this condition upon loading the starlog.  If there is a null designation found the two user should be warned and given a chance to either fix or delete the nefarious line.

**Comment by ermaier** [comment]
Added capability to automatically detect missing "type star" designations and insert an "X", which will still result in a successful import of that line.
