### ISSUE TITLE
Greyed Out Button Box

### ISSUE THREAD

**Issue by jaisen1** [Navy-Precision-Optial-Interferometer/PYBOC#5]
Looking at the baseline offset selector boxes I see that 'b4' is greyed out and the others are all white.  Is this cosmetic or is there an underlying reason such as PYBOC thinks there is no data for this baseline?  Using the 2021-08-25 starlog I am still able to plot up data for the 'b4' baseline so not sure why it is greyed out.

**Comment by ermaier** [comment]
This is cosmetic. The way the checkbox widget works, the background color of the box that contains the checkmark is one variable, and the color of the checkmark/the label text is another variable. I.e the text is white so so is the checkmark. So grey background to make it visible.

**Comment by ermaier** [comment]
Changed background colors of the checkmark boxes to be more uniform so b4 doesn't stand out.
