### ISSUE TITLE
Hour Angle Calculation

### ISSUE THREAD

**Issue by SolvayB** [Navy-Precision-Optial-Interferometer/PYBOC#6]
Is there a way to add an hour angle calculator into the PyBOC tool using current LST? 

While operating it has been difficult to try and grab accurate offsets for the hour angle of the object we are slewing to. If there is some way we can incorporate updating baseline offsets more accurately with the change of hour angle that would be helpful to just be able to glance over to the calculator and grab updated values. 

Let me know if you have any questions!

**Comment by jaisen1** [comment]
As a quick follow up here.  I do not think we want to calculate the hour angle of the current LST but rather the hour angle of the selected target using it's RA and DEC.  If this is possible it might also be worth considering adding in an additional "human factors" offset to the time....say add an additional (actually subtracting) 30 seconds to the HA to account for our inefficiencies as humans.

**Comment by ermaier** [comment]
Automatic calculation of hour angle/updated offsets has been added. They will update every 10 seconds at present; let me know if you feel this should be changed.
